platform_names = ["ORCID",
    "Google Scholar",
    "Wikidata",
    "VIAF",
    "DBLP",
    "Dimensions",
    "Github",
    "Microsoft Academic",
    "Semantic Scholar",
    "DNB/GNB",
    "ACM Digital Library"]
